oc_reservation_home:
    path:     /
    defaults: { _controller: OCReservationBundle:Commande:index }

oc_reservation_billet:
    path:     /billet
    defaults: { _controller: OCReservationBundle:Commande:billet }

oc_reservation_recapitulatif:
    path:     /recapitulatif
    defaults: { _controller: OCReservationBundle:Commande:recapitulatif }

oc_reservation_checkout:
    path:     /checkout
    defaults: { _controller: OCReservationBundle:Commande:checkout }