services:
    OCReservationBundle:Prix:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - OC\ReservationBundle\Entity\Prix

    OCReservationBundle:Commande:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - OC\ReservationBundle\Entity\Commande            

    oc_reservation.prixbillet:
        class: OC\ReservationBundle\PrixBillet\OCPrixBillet
        arguments:
            - "@OCReservationBundle:Prix"

    oc_reservation.prixtotal:
        class: OC\ReservationBundle\PrixTotal\OCPrixTotal

    oc_reservation.stripepaiement:
        class: OC\ReservationBundle\StripePaiement\OCStripePaiement

    oc_reservation.envoibillet:
        class: OC\ReservationBundle\EnvoiBillet\OCEnvoiBillet
        arguments: ["@mailer", "@templating"]

    oc_reservation.codebillet:
        class: OC\ReservationBundle\CodeBillet\OCCodeBillet

    oc_reservation.billetcommande:
        class: OC\ReservationBundle\BilletCommande\OCBilletCommande

    oc_reservation.validator.typedate:                              
        class: OC\ReservationBundle\Validator\TypeDateValidator    
        tags:
            - { name: validator.constraint_validator, alias: oc_reservation_typedate }

    oc_reservation.validator.capacitemax:                              
        class: OC\ReservationBundle\Validator\CapaciteMaxValidator
        arguments:
            - "@OCReservationBundle:Commande"    
        tags:
            - { name: validator.constraint_validator, alias: oc_reservation_capacitemax }  