services:
    oc_reservation.prixbillet:
        class: OC\ReservationBundle\PrixBillet\OCPrixBillet
        arguments:
            - "@OCReservationBundle:Prix"

    oc_reservation.prixtotal:
        class: OC\ReservationBundle\PrixTotal\OCPrixTotal

    OCReservationBundle:Prix:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - OC\ReservationBundle\Entity\Prix